CREATE TABLE `daily_editions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`editionDate` varchar(10) NOT NULL,
	`editionNumber` int NOT NULL,
	`headline` varchar(500) NOT NULL,
	`editorialP1` text NOT NULL,
	`editorialP2` text NOT NULL,
	`editorialP3` text NOT NULL,
	`imageCaption` varchar(500) NOT NULL,
	`statsTitle` varchar(300) NOT NULL,
	`stat1Number` int NOT NULL,
	`stat1Suffix` varchar(10) NOT NULL,
	`stat1Label` varchar(100) NOT NULL,
	`stat1Desc` varchar(500) NOT NULL,
	`stat1Source` varchar(200) NOT NULL,
	`stat2Number` int NOT NULL,
	`stat2Suffix` varchar(10) NOT NULL,
	`stat2Label` varchar(100) NOT NULL,
	`stat2Desc` varchar(500) NOT NULL,
	`stat2Source` varchar(200) NOT NULL,
	`stat3Number` int NOT NULL,
	`stat3Suffix` varchar(10) NOT NULL,
	`stat3Label` varchar(100) NOT NULL,
	`stat3Desc` varchar(500) NOT NULL,
	`stat3Source` varchar(200) NOT NULL,
	`quote` text NOT NULL,
	`ctaTitle` varchar(300) NOT NULL,
	`ctaText` text NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `daily_editions_id` PRIMARY KEY(`id`),
	CONSTRAINT `daily_editions_editionDate_unique` UNIQUE(`editionDate`)
);
